export const SET_USER_ID = 'SET_USER_ID'

export const SET_ROOMS_LOADED_STATE = 'SET_ROOMS_LOADED_STATE'
export const SET_ROOMS = 'SET_ROOMS'
export const ADD_ROOM = 'ADD_ROOM'
export const DELETE_ROOM = 'DELETE_ROOM'
export const SET_ROOM_ID = 'SET_ROOM_ID'

export const ROOM_SET_USERS = 'ROOM_SET_USERS'
export const ROOM_JOIN_USER = 'ROOM_JOIN_USER'
export const ROOM_LEAVE_USER = 'ROOM_LEAVE_USER'

export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_NEXT_MSGID = 'SET_NEXT_MSGID'
export const INC_NEXT_MSGID = 'INC_NEXT_MSGID'
export const INIT_MESSAGE = 'INIT_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
export const EDIT_MESSAGE = 'EDIT_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'

export const ATTACH_FILE = 'ATTACH_FILE'
export const UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT'
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS'

export const LEAVE_REACTION = 'LEAVE_REACTION'
export const REMOVE_REACTION = 'REMOVE_REACTION'
