name: compile assets

on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: corepack enable

      - name: Install Yarn dependencies
        run: yarn install

      - name: Compile assets
        run: yarn build

      - name: Commit compiled files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Compile Assets
          file_pattern: public/
